server:
  port: ${PORT:8080}
  servlet:
    context-path:


spring:
  data:
    rest:
      detection-strategy: annotated

  datasource:
    url: jdbc:h2:~/db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver

  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect